const $=s=>document.querySelector(s); let token=localStorage.getItem("gurukul_token"); let me=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...(token?{Authorization:"Bearer "+token}:{})};if(opt.body&&typeof opt.body!=="string"){opt.headers["Content-Type"]="application/json";opt.body=JSON.stringify(opt.body)}const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||"Request failed");return d}
function modal(html){$("#modalBody").innerHTML=html;$("#modal").classList.remove("hidden")} function closeModal(){$("#modal").classList.add("hidden")}
function loginModal(){modal(`<h2>Student Login</h2><form id="loginForm" class="form"><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Password" required><button class="btn">Login</button></form><p>No account? <a href="#" onclick="registerModal();return false">Create one</a></p>`);$("#loginForm").onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target),d=await api("/api/auth/login",{method:"POST",body:Object.fromEntries(f)});token=d.token;localStorage.setItem("gurukul_token",token);closeModal();refresh()}catch(x){alert(x.message)}}}
function registerModal(){modal(`<h2>Create student account</h2><form id="regForm" class="form"><input name="name" placeholder="Full name" required><input name="email" type="email" placeholder="Email" required><input name="phone" placeholder="Mobile"><input name="password" type="password" placeholder="Password" minlength="6" required><button class="btn">Register</button></form>`);$("#regForm").onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target),d=await api("/api/auth/register",{method:"POST",body:Object.fromEntries(f)});token=d.token;localStorage.setItem("gurukul_token",token);closeModal();refresh()}catch(x){alert(x.message)}}}
async function loadCourses(){const cs=await api("/api/courses");$("#courseGrid").innerHTML=cs.map(c=>`<article class="card"><div class="courseIcon">${esc(c.category)}</div><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><strong>₹${Number(c.price).toLocaleString("en-IN")}</strong><button class="btn full" onclick="course(${c.id})">View course</button></article>`).join("")}
async function course(id){const c=await api("/api/courses/"+id);modal(`<span class="eyebrow">${esc(c.category)}</span><h2>${esc(c.title)}</h2><p>${esc(c.description)}</p><h3>What you get</h3><ul>${c.lessons.map(l=>`<li>${esc(l.title)}</li>`).join("")||"<li>Content coming soon</li>"}</ul><button class="btn full" onclick="enroll(${c.id})">${c.price?"Enroll / Continue":"Enroll Free"}</button>`)}
async function enroll(id){if(!token){loginModal();return}try{const d=await api("/api/enroll/"+id,{method:"POST"});alert(d.message);if(d.payment_status==="pending") alert("For live payments, configure Razorpay in .env. This demo does not fake a successful payment.");closeModal();}catch(e){alert(e.message)}}
async function loadNotices(){const n=await api("/api/notices");$("#noticesList").innerHTML=n.map(x=>`<div class="notice"><b>${esc(x.title)}</b><p>${esc(x.body)}</p></div>`).join("")}
async function refresh(){try{me=await api("/api/me");$("#loginBtn").textContent=me.name.split(" ")[0]+" • Dashboard";$("#loginBtn").onclick=dashboard}else{$("#loginBtn").onclick=loginModal}}
async function dashboard(){const d=await api("/api/student/dashboard");modal(`<div class="dash"><h2>Welcome, ${esc(me.name)}</h2><div class="dashgrid">${d.courses.map(c=>`<div class="card"><h3>${esc(c.title)}</h3><span class="tag">${esc(c.payment_status)}</span><button class="btn full" onclick="openLearning(${c.id})">My Course</button></div>`).join("")||"<p>No enrolled courses yet.</p>"}</div><h3>Results</h3>${d.results.map(r=>`<div class="notice">${esc(r.title)} — <b>${r.score}/${r.total}</b></div>`).join("")||"<p>No test attempts yet.</p>"}<button class="btn ghost" onclick="logout()">Logout</button></div>`)}
async function openLearning(id){try{const c=await api("/api/student/course/"+id);modal(`<h2>${esc(c.title)}</h2><div>${c.lessons.map(l=>`<article class="lesson"><h3>${esc(l.title)}</h3>${l.video_url?`<div class="video"><iframe src="${esc(l.video_url)}" allowfullscreen></iframe></div>`:""}${l.notes_url?`<a class="btn ghost" href="${esc(l.notes_url)}" target="_blank">Open Notes / PDF</a>`:""}</article>`).join("")}</div><h3>Tests</h3>${c.tests.map(t=>`<button class="btn" onclick="takeTest(${t.id})">${esc(t.title)} (${t.duration_minutes} min)</button>`).join(" ")||"<p>No tests yet.</p>"}`)}catch(e){alert(e.message)}}
async function takeTest(id){try{const t=await api("/api/tests/"+id);modal(`<h2>${esc(t.title)}</h2><form id="testForm" class="testform">${t.questions.map((q,i)=>`<fieldset><legend>${i+1}. ${esc(q.question)}</legend>${["A","B","C","D"].map(k=>`<label><input type="radio" name="q${q.id}" value="${k}"> ${esc(q["option_"+k.toLowerCase()])}</label>`).join("")}</fieldset>`).join("")}<button class="btn">Submit Test</button></form>`);$("#testForm").onsubmit=async e=>{e.preventDefault();const answers={};new FormData(e.target).forEach((v,k)=>answers[k.slice(1)]=v);try{const r=await api("/api/tests/"+id+"/submit",{method:"POST",body:{answers}});modal(`<h2>Result</h2><div class="result">${r.score} / ${r.total}<small>${r.percentage}%</small></div><button class="btn" onclick="dashboard()">Back to Dashboard</button>`)}catch(x){alert(x.message)}}}catch(e){alert(e.message)}}
function logout(){token=null;localStorage.removeItem("gurukul_token");closeModal();refresh()}
$("#leadForm").onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);await api("/api/leads",{method:"POST",body:Object.fromEntries(f)});$("#leadMsg").textContent=" Enquiry received. We'll contact you.";e.target.reset()}catch(x){$("#leadMsg").textContent=" "+x.message}}
$("#loginBtn").onclick=loginModal;loadCourses();loadNotices();refresh();